# Generated by Django 5.0.7 on 2024-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alert',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
